Repository MirrorNetworking/Mirror, pull requests merged in 2019-03, with the labels that each got.

#588 Remove a per packet Encoding allocation
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
Labels: Needs Testing

#611 feature: Mirror List Server example
  Assets/Mirror/Examples/ListServer.meta
  Assets/Mirror/Examples/ListServer/ListServer.cs
  Assets/Mirror/Examples/ListServer/ListServer.cs.meta
  Assets/Mirror/Examples/ListServer/Scenes.meta
  Assets/Mirror/Examples/ListServer/Scenes/NavMesh.asset
  Assets/Mirror/Examples/ListServer/Scenes/NavMesh.asset.meta
  Assets/Mirror/Examples/ListServer/Scenes/Scene.unity
  Assets/Mirror/Examples/ListServer/Scenes/Scene.unity.meta
  Assets/Mirror/Examples/ListServer/UI.meta
  Assets/Mirror/Examples/ListServer/UI/ServerStatusSlot.prefab
  Assets/Mirror/Examples/ListServer/UI/ServerStatusSlot.prefab.meta
  Assets/Mirror/Examples/ListServer/UI/UIServerStatusSlot.cs
  Assets/Mirror/Examples/ListServer/UI/UIServerStatusSlot.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: work in progress

#602 feat(syncvar): Add SyncDictionary
  Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs.meta
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Runtime/SyncDictionary.cs
  Assets/Mirror/Runtime/SyncDictionary.cs.meta
  Assets/Mirror/Tests/SyncDictionaryTest.cs
  Assets/Mirror/Tests/SyncDictionaryTest.cs.meta
  docs/Classes/SyncDictionary.md
  docs/Concepts/StateSync.md
Labels: work in progress

#642 Add the name of the Message back to the debug
  Assets/Mirror/Runtime/NetworkClient.cs
Labels: enhancement
