Repository MirrorNetworking/Mirror, pull requests merged in 2019-10, with the labels that each got.

#1134 Obsoletes OnServerAddPlayer
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine

#1156 Remove unnecessary virtuals
  Assets/Mirror/Runtime/NetworkConnection.cs
Labels: PassedTestRoutine

#1162 fix: Prevent NRE
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, bug

#1161 Refresh Data For Preview Window
  Assets/Mirror/Editor/NetworkInformationPreview.cs
Labels: PassedTestRoutine, enhancement

#1163 Rename includeSelf to includeOwner
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1153 feat: Users may provide custom serializers for any type
  Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Tests/WeaverTest.cs
Labels: PassedTestRoutine, enhancement, work in progress

#1146 SyncList custom Equality Comparer support
  Assets/Mirror/Runtime/SyncList.cs
Labels: enhancement

#1158 fix: Don't give host player authority by default
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, bug

#1091 feat: Add Timeout to NetworkAuthenticator
  .gitignore
  Assets/Mirror/Runtime/NetworkAuthenticator.cs
  doc/Components/Authenticators/Basic.png
  doc/Guides/Authentication.md
Labels: PassedTestRoutine, enhancement

#1169 fix: Suspend server transport while changing scenes
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1168 feat: Remove Command shortcut for host mode, fix #1160
  Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
Labels: PassedTestRoutine, enhancement

#1178 Remove Authority Set
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1175 refactor: Split NC for clients and servers
  Assets/Mirror/Runtime/LocalConnections.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkConnectionToClient.cs
  Assets/Mirror/Runtime/NetworkConnectionToClient.cs.meta
  Assets/Mirror/Runtime/NetworkConnectionToServer.cs
  Assets/Mirror/Runtime/NetworkConnectionToServer.cs.meta
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1180 Remove redundant force authority
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1179 Destroy objects owned by this connection when disconnecting
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkConnectionToClient.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1187 Simplify local player setting
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: work in progress

#1192 breaking: Remove localPlayerAuthority
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Editor/NetworkIdentityEditor.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine

#1195 refactor: Simplify spawn message
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement
