Repository MirrorNetworking/Mirror, pull requests merged in 2019-11, with the labels that each got.

#1199 refactor: remove pending Owner
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1200 refactor: reuse connectionToClient for authority
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Editor/NetworkInformationPreview.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1204 feat: SyncToOwner now works with authority
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1206 perf: spawn with client authority only takes 1 message
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1208 refactor: Remove special case for host mode
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1210 Deprecate SpawnWithClientAuthority
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1209 refactor: Simplify spawning player
  Assets/Mirror/Runtime/ClientScene.cs
Labels: PassedTestRoutine, enhancement

#1215 feat: Pass SpawnMessage to spawn handler
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/UNetwork.cs
Labels: PassedTestRoutine, enhancement

#1217 feat: Script Templates
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt.meta
  Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt
  Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt.meta
  Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt
  Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt.meta
  Assets/ScriptTemplates/53-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt
  Assets/ScriptTemplates/53-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt.meta
  Assets/ScriptTemplates/54-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt
  Assets/ScriptTemplates/54-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt.meta
Labels: enhancement

#1222 fix: set isClient before Start() is called
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, bug, regression

#1223 fix: set isServer before object starts
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine

#1233 Replaces SpawnWithClientAuthority with Spawn Overloads
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1240 Made RandomColor a Separate Component
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/RandomColor.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/RandomColor.cs.meta
  Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
  Assets/Mirror/Examples/Room/Prefabs/Prize.prefab
  Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Room/Scripts/RandomColor.cs
  Assets/Mirror/Examples/Room/Scripts/RandomColor.cs.meta
  Assets/Mirror/Examples/Room/Scripts/Reward.cs
  Assets/Mirror/Examples/Room/Scripts/Spawner.cs
Labels: PassedTestRoutine, enhancement

#1246 fix: remove problematic OnSpawnMessageForLocalPlayer
  Assets/Mirror/Runtime/ClientScene.cs
Labels: PassedTestRoutine, enhancement

#1249 fix: Call hooks when initializing objects OnStartServer on host
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, bug

#1251 fix: hasAuthority is now visible in all overrides
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1252 fix: isClient now reports true onStartServer in host mode
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1253 fix: isLocalPlayer works in host mode onStartServer
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1254 fix: replacing the player does not mean giving up authority
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1255 fix: isLocalPlayer is true during OnStartClient for Player
  Assets/Mirror/Runtime/ClientScene.cs
Labels: PassedTestRoutine, enhancement

#1248 Spawn host objects via spawn, just like clients
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1258 Simplify isServer
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1259 fix: issue with more than 1 client
  Assets/Mirror/Runtime/ClientScene.cs
Labels: PassedTestRoutine, bug, regression
