Repository MirrorNetworking/Mirror, pull requests merged in 2019-05, with the labels that each got.

#853 Avoid memory leak from cloned materials
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Lobby/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Lobby/Scripts/Reward.cs
Labels: PassedTestRoutine, enhancement

#644 feat(scene): Add support for scene loading params
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Tests/MessagePackerTest.cs
Labels: PassedTestRoutine

#862 fix: Add channelId to NetworkClient.Send Method
  Assets/Mirror/Runtime/NetworkClient.cs
Labels: PassedTestRoutine

#866 fix(NetworkManager): ClientChangeScene always (re)loads the networkSceneName instead of newSceneName
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#867 fix(NetworkManager) : properly load scene on clients using new load parameters
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug
