Repository MirrorNetworking/Mirror, pull requests merged in 2019-09, with the labels that each got.

#1047 feat: custom reader/writer via extension methods
  Assets/Mirror/Editor/Weaver/Extensions.cs
  Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs.meta
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
  Assets/Mirror/Tests/CustomRWTest.cs
  Assets/Mirror/Tests/CustomRWTest.cs.meta
Labels: enhancement

#982 Updated Pong 2
  Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
  Assets/Mirror/Examples/Pong/Scenes/Scene.unity
  Assets/Mirror/Examples/Pong/Scripts/Ball.cs
  Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
  Assets/Mirror/Examples/Pong/Scripts/Player.cs
Labels: enhancement

#1052 fix: error with missing assemblies
  Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
Labels: PassedTestRoutine

#1049 Don't call Ready if we're ready already
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine

#1056 fix: code generation works with il2cpp again
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Labels: regression

#1054 Add check for sceneMode
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine

#1066 Don't reload offline scene
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1071 doc: Add XML comments to Custom Attributes
  Assets/Mirror/Runtime/CustomAttributes.cs
Labels: docs

#1057 feat: Authentication Framework
  Assets/Mirror/Authenticators.meta
  Assets/Mirror/Authenticators/BasicAuthenticator.cs
  Assets/Mirror/Authenticators/BasicAuthenticator.cs.meta
  Assets/Mirror/Authenticators/Mirror.Authenticators.asmdef
  Assets/Mirror/Authenticators/Mirror.Authenticators.asmdef.meta
  Assets/Mirror/Runtime/NetworkAuthenticator.cs
  Assets/Mirror/Runtime/NetworkAuthenticator.cs.meta
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  doc/articles/Concepts/Authentication.md
  doc/articles/Concepts/BasicAuthentication.PNG
Labels: PassedTestRoutine, enhancement

#1089 feat: Secure messages that require authentication, fixes #720
  Assets/Mirror/Authenticators/BasicAuthenticator.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1093 Redefine SceneMessage
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/AdditiveScenes/Scripts/SceneLoader.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/SceneLoader.cs.meta
  Assets/Mirror/Examples/AdditiveScenes/Scripts/ZoneHandler.cs
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Tests/MessagePackerTest.cs
Labels: PassedTestRoutine, enhancement

#1092 Rename NetworkConnection.playerController to identity
  Assets/Mirror/Components/NetworkProximityChecker.cs
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Editor/NetworkIdentityEditor.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/ShootingTankBehaviour.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1094 Update NetworkRoomPlayer.cs
  Assets/Mirror/Components/NetworkRoomPlayer.cs
Labels: work in progress

#1113 Make RemoveClientAuthority easier to use
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1114 Remove Host Migration cruft
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1119 merge NetworkConnection.SendBytes and TransportSend
  Assets/Mirror/Runtime/NetworkConnection.cs
Labels: enhancement

#1120 feat: Transport can send to multiple connections at once
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/Transport/Transport.cs
Labels: enhancement

#1124 Transports now give the channel when receiving message
  Assets/Mirror/Runtime/LocalConnections.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkMessage.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs
  Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
  Assets/Mirror/Runtime/Transport/Transport.cs
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Labels: work in progress

#1103 breaking: allocation free sends
  Assets/Mirror/Editor/PreprocessorDefine.cs
  Assets/Mirror/Runtime/LocalConnections.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs
  Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
  Assets/Mirror/Runtime/Transport/Transport.cs
  Assets/Mirror/Runtime/Transport/Websocket/Client.cs
  Assets/Mirror/Runtime/Transport/Websocket/Server.cs
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
  Assets/Mirror/Tests/CustomRWTest.cs
Labels: PassedTestRoutine, enhancement

#1090 Describe cleaner way to add customizable character
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/Messages.cs
  doc/Guides/CustomPlayer.md
  doc/Guides/toc.yml
Labels: docs, enhancement
