Repository MirrorNetworking/Mirror, pull requests merged in 2019-12, with the labels that each got.

#1265 Improve Turn and Jump & Add Velocity
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
Labels: enhancement

#1266 Move scoring to PlayerScore
  Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
  Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs.meta
  Assets/Mirror/Examples/Room/Scripts/Reward.cs
Labels: enhancement

#1268 Add Return button to Room Manager
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: enhancement

#1269 Require Network Transform
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
Labels: enhancement

#1267 Restore Room Player Authority
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: bug

#1276 Removed non-implemented overload
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Labels: bug

#1261 fix: replace player (remove authority by default)
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1272 remove SyncDictionary.Dirty function because it's unused and we removed it for SyncList already too
  Assets/Mirror/Runtime/SyncDictionary.cs
Labels: PassedTestRoutine

#1277 Add true for keepAuthority
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: bug, regression

#1281 Fix ServerChangeScene
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: bug

#1280 fix: ReplacePlayer now calls OnStartLocalPlayer
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: bug

#1286 feat: Mirror now supports message inheritance
  Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
  Assets/Mirror/Tests/MessageInheritanceTest.cs
  Assets/Mirror/Tests/MessageInheritanceTest.cs.meta
Labels: PassedTestRoutine, enhancement

#1288 Make startPositionIndex public
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: enhancement

#1290 fix: Inspector Refresh for SyncVars
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: bug

#1291 fix: Draw SyncVar label for Unity objects inline
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: bug, enhancement

#1292 Add ScriptTemplates to GitHub UnityPackager
  appveyor.yml
Labels: enhancement

#1284 feat: telepathy can now receive port from uri
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Labels: enhancement

#1287 feat: websocket can receive port in url
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Labels: enhancement

#1299 Unused isOwner
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1300 No point in calling this here
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1298 Restore clientAuthorityCallback
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, regression

#1302 Fix Delayed Disconnect
  Assets/Mirror/Authenticators/BasicAuthenticator.cs
Labels: PassedTestRoutine, bug

#1303 fix: error when there are no network behaviors
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, bug

#1316 Added video tutorial link.
  doc/Components/NetworkTransformChild.md
Labels: docs

#1315 Added video tutorial link.
  doc/Components/NetworkTransform.md
Labels: docs

#1314 Added SyncVar hook video link.
  doc/Guides/Sync/SyncVarHook.md
Labels: docs

#1313 Changedvideo link to video within playlist.
  doc/Guides/Sync/SyncVars.md
Labels: docs

#1312 Added video tutorial.
  doc/Guides/Communications/RemoteActions.md
Labels: docs

#1311 Added missing field setter on Item ReadItem() for ARMOR.
  doc/Guides/DataTypes.md
Labels: docs

#1317 feat: Add roomPlayer parameter to OnRoomServerCreateGamePlayer
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/ScriptTemplates/53-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt
Labels: PassedTestRoutine, enhancement

#1318 Adjust cameras for server view
  Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Room/Scenes/OnlineScene.unity
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
Labels: PassedTestRoutine, enhancement

#1327 Remove usings
  Assets/Mirror/Components/NetworkLobbyManager.cs
  Assets/Mirror/Components/NetworkLobbyPlayer.cs
  Assets/Mirror/Editor/Weaver/Helpers.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
  Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
  Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkConnectionToClient.cs
  Assets/Mirror/Runtime/NetworkConnectionToServer.cs
  Assets/Mirror/Runtime/NetworkDiagnostics.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Client.cs
  Assets/Mirror/Runtime/Transport/Websocket/Client.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/BufferPool.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/InvalidHttpResponseCodeException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/SecWebSocketKeyMissingException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/ServerListenerSocketException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/WebSocketBufferOverflowException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/WebSocketHandshakeFailedException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Exceptions/WebSocketVersionNotSupportedException.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/HttpHelper.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/IBufferPool.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketFrameWriter.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/PongEventArgs.cs
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/WebSocketClientOptions.cs
  Assets/Mirror/Runtime/Transport/Websocket/Server.cs
  Assets/Mirror/Tests/LocalConnectionTest.cs
  Assets/Mirror/Tests/SyncVarTest.cs
  Assets/Mirror/Tests/WeaverTest.cs
Labels: PassedTestRoutine, enhancement

#1305 feat: Chat example
  Assets/Mirror/Examples/Chat.meta
  Assets/Mirror/Examples/Chat/Prefabs.meta
  Assets/Mirror/Examples/Chat/Prefabs/Player.prefab
  Assets/Mirror/Examples/Chat/Prefabs/Player.prefab.meta
  Assets/Mirror/Examples/Chat/Scenes.meta
  Assets/Mirror/Examples/Chat/Scenes/Main.unity
  Assets/Mirror/Examples/Chat/Scenes/Main.unity.meta
  Assets/Mirror/Examples/Chat/Scripts.meta
  Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
  Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs.meta
  Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
  Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs.meta
  Assets/Mirror/Examples/Chat/Scripts/Player.cs
  Assets/Mirror/Examples/Chat/Scripts/Player.cs.meta
Labels: enhancement

#1329 feat: Allow Custom Scene Handling
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Labels: PassedTestRoutine, enhancement

#1349 Made loadingSceneAsync public
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1352 fix: destroy owned objects
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, bug, regression

#1358 Add Meta Files
  Assets/Mirror/Tests/Castle.Core.dll.meta
  Assets/Mirror/Tests/NSubstitute.dll.meta
  Assets/Mirror/Tests/System.Threading.Tasks.Extensions.dll.meta
Labels: PassedTestRoutine

#1357 Call OnClientConnect in FinishLoadScene
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1361 feat: add version to package file
  .releaserc.yml
Labels: enhancement
