Repository MirrorNetworking/Mirror, pull requests merged in 2019-08, with the labels that each got.

#995 XML Summary Comments
  .gitignore
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Components/NetworkLobbyManager.cs
  Assets/Mirror/Components/NetworkLobbyPlayer.cs
  Assets/Mirror/Components/NetworkProximityChecker.cs
  Assets/Mirror/Components/NetworkTransformChild.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkManagerHUD.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/NetworkStartPosition.cs
Labels: docs, enhancement

#1001 Fix unused ex warnings in websockets
  Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs
  Assets/Mirror/Runtime/Transport/Websocket/Server.cs
Labels: bug

#1002 Internalize OnServerAddPlayer Safety Checks
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine

#1016 fix: Rebuild observers when we switch scenes, fixes #978
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine

#1017 fix: syncvar hooks should not affect each other, fixes #1015
  Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
Labels: PassedTestRoutine

#1018 refactor: simplify owner initialization
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1029 fix appveyor build error
  appveyor.yml
Labels: work in progress

#1023 feat: component based SyncToOwner, fixes #39
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/SyncVarTest.cs
Labels: PassedTestRoutine
