Repository MirrorNetworking/Mirror, pull requests merged in 2019-04, with the labels that each got.

#795 minimum changeset for cecil 0.10.3
  Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
  Assets/Mirror/Editor/Weaver/Program.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Plugins/Mono.Cecil.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Mdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Mdb.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Pdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Pdb.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Rocks.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Rocks.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.dll.meta
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Mdb.dll
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Mdb.pdb
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Mdb.pdb.meta
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Pdb.dll
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Pdb.pdb
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.Pdb.pdb.meta
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.dll
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.pdb
  Assets/Mirror/Plugins/Unity.Cecil/Unity.Cecil.pdb.meta
Labels: enhancement

#827 fix: #718 remove Tests folder from unitypackage
  appveyor.yml
Labels: work in progress

#832 fix: Mono.CecilX namespace to work around Unity 2019 Cecil namespace collision
  Assets/Mirror/Editor/Weaver/Extensions.cs
  Assets/Mirror/Editor/Weaver/Helpers.cs
  Assets/Mirror/Editor/Weaver/Mirror.Weaver.asmdef.meta
  Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
  Assets/Mirror/Editor/Weaver/Program.cs
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/Resolvers.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Mdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Pdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.Rocks.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.Cecil.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Mdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Mdb.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Pdb.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Pdb.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Rocks.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Rocks.dll.meta
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.dll
  Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.dll.meta
Labels: 2019.1
