Repository MirrorNetworking/Mirror, pull requests merged in 2020-03, with the labels that each got.

#1552 fix: #1548 Adding PropertyDrawer for SyncVar
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
  Assets/Mirror/Editor/SyncVarAttributeDrawer.cs
  Assets/Mirror/Editor/SyncVarAttributeDrawer.cs.meta
  Assets/Mirror/Runtime/CustomAttributes.cs
Labels: PassedTestRoutine, bug

#1554 fix: Prevent Double Call of NetworkServer.Destroy
  Assets/Mirror/Runtime/NetworkIdentity.cs
  doc/General/ChangeLog.md
Labels: PassedTestRoutine, bug

#1547 feat: Add IsParameterControlledByCurve check to NetworkAnimator
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: enhancement

#1545 fix: Change LogError to Log. Added more details.
  Assets/Mirror/Runtime/NetworkConnection.cs
Labels: bug, work in progress

#1573 moving code to its own class
  Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs.meta
Labels: PassedTestRoutine, enhancement

#1575 fix: Added LogFilter.Debug check in a few places
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1569 Fixing exceptions
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: bug

#1574 Weaver test for adding guard code
  Assets/Mirror/Editor/Weaver/AssemblyInfo.cs
  Assets/Mirror/Editor/Weaver/AssemblyInfo.cs.meta
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
  Assets/Mirror/Tests/Editor/WeaverTest.cs
  Assets/Mirror/Tests/Editor/WeaverTests~/NetworkBehaviourClient.cs
  Assets/Mirror/Tests/Editor/WeaverTests~/NetworkBehaviourServer.cs
Labels: PassedTestRoutine, enhancement

#1578 fix: Make SendToReady non-ambiguous
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, bug

#1592 Remove Usage of LAN in HUD and Docs
  Assets/Mirror/Examples/AdditiveScenes/README.md
  Assets/Mirror/Examples/Basic/README.md
  Assets/Mirror/Examples/Room/README.md
  Assets/Mirror/Runtime/NetworkManagerHUD.cs
  doc/Components/NetworkManagerHUD.md
  doc/Components/NetworkManagerHUDUI.png
  doc/Examples/Pong/index.md
  doc/index.md
Labels: PassedTestRoutine, docs, enhancement

#1576 feat: now you can assign scenes even if not in Editor
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Components/NetworkRoomPlayer.cs
  Assets/Mirror/Editor/SceneDrawer.cs
  Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
  Assets/Mirror/Examples/Room/Scenes/OfflineScene.unity
  Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: enhancement

#1601 fix: #1515 - StopHost now invokes OnServerDisconnected for the host client too
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Editor/NetworkManagerStopHostOnServerDisconnectedTest.cs
  Assets/Mirror/Tests/Editor/NetworkManagerStopHostOnServerDisconnectedTest.cs.meta
  Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
Labels: work in progress

#1602 NetworkManager.StopHost stops client, then server. Seems more consistent this way.
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PendingTestRoutine

#1616 perf: faster NetworkWriter pooling
  Assets/Mirror/Runtime/NetworkWriterPool.cs
Labels: work in progress

#1619 fix: MissingReferenceException
  Assets/Mirror/Editor/NetworkInformationPreview.cs
Labels: bug, regression
