Repository MirrorNetworking/Mirror, pull requests merged in 2020-06, with the labels that each got.

#1827 fix: Better errors when trying to replace existing assetid
  Assets/Mirror/Runtime/AssemblyInfo.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Tests/Common/ClientSceneTestsBase.cs
  Assets/Mirror/Tests/Common/ClientSceneTestsBase.cs.meta
  Assets/Mirror/Tests/Common/ClientSceneTests_RegisterPrefabBase.cs
  Assets/Mirror/Tests/Common/ClientSceneTests_RegisterPrefabBase.cs.meta
  Assets/Mirror/Tests/Editor/ClientSceneTests_RegisterPrefab.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
  Assets/Mirror/Tests/Runtime/ClientSceneTests_Runtime_RegisterPrefab.cs
  Assets/Mirror/Tests/Runtime/ClientSceneTests_Runtime_RegisterPrefab.cs.meta
Labels: PassedTestRoutine, enhancement

#1971 fix: Replacing ClearDelegates with RemoveDelegates for test
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
  Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Labels: PassedTestRoutine, enhancement

#1984 docs: updating example and adding comments
  doc/Guides/Sync/index.md
Labels: docs

#1987 docs: replacing paragraph on return with is dirty
  doc/Guides/Sync/index.md
Labels: docs

#1986 docs: hooks are called on initialState too
  doc/Guides/Sync/index.md
Labels: docs

#1985 docs: sync vars now work with overriden OnSerialize
  doc/Guides/Sync/index.md
Labels: docs

#1989 breaking: Websocket Transport now requires full path to PFX
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Labels: PassedTestRoutine, enhancement, websockets

#1990 feat: Experimental Network Transform
  Assets/Mirror/Components/Experimental.meta
  Assets/Mirror/Components/Experimental/NetworkTransform.cs
  Assets/Mirror/Components/Experimental/NetworkTransform.cs.meta
  Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
  Assets/Mirror/Components/Experimental/NetworkTransformBase.cs.meta
  Assets/Mirror/Components/Experimental/NetworkTransformChild.cs
  Assets/Mirror/Components/Experimental/NetworkTransformChild.cs.meta
Labels: PassedTestRoutine, enhancement

#1996 Update Attributes.md
  doc/Guides/Attributes.md
Labels: docs

#2001 feat: adding log handler that sets console color
  Assets/Mirror/Runtime/Logging/ConsoleColorLogHandler.cs
  Assets/Mirror/Runtime/Logging/ConsoleColorLogHandler.cs.meta
  Assets/Mirror/Runtime/Logging/NetworkHeadlessLogger.cs
  Assets/Mirror/Runtime/Logging/NetworkHeadlessLogger.cs.meta
  doc/Components/NetworkHeadlessLogger.md
  doc/Components/NetworkHeadlessLogger.png
  doc/Components/index.md
Labels: enhancement

#1822 feat: Experimental NetworkRigidBody
  Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
  Assets/Mirror/Components/Experimental/NetworkRigidbody.cs.meta
Labels: enhancement, work in progress
