Repository MirrorNetworking/Mirror, pull requests merged in 2020-12, with the labels that each got.

#2484 breaking: Unity LLAPI transport meets the recycle bin.
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: Breaking Change

#2478 feat: Allow Networkbehaviours to be sent in rpc
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/WeaverTypes.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
  Assets/Mirror/Tests/Editor/NetworkWriterCollectionTest.cs
  Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
  Assets/Mirror/Tests/Editor/RpcNetworkIdentityTest.cs
  Assets/Mirror/Tests/Editor/RpcNetworkIdentityTest.cs.meta
  Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
  Assets/Mirror/Tests/Editor/Weaver/WeaverClientRpcTests.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverClientRpcTests~/BehaviourCanBeSentInRpc.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests.cs
Labels: Awaiting Rreview

#2471 feat: allow types that inherit from Networkbehaviour to be used in syncvar's
  Assets/Mirror/Editor/Weaver/Extensions.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/WeaverTypes.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
  Assets/Mirror/Tests/Editor/SyncVarHookTest.cs
  Assets/Mirror/Tests/Editor/SyncVarTest.cs
  Assets/Mirror/Tests/Editor/SyncVarTestBase.cs
  Assets/Mirror/Tests/Editor/SyncVarTestBase.cs.meta
Labels: Awaiting Rreview

#2495 Make IDisposable classes sealed
  Assets/Mirror/Runtime/NetworkReaderPool.cs
  Assets/Mirror/Runtime/NetworkWriterPool.cs
Labels: enhancement

#2499 feat: Multiple Matches Example using Match Checker
  Assets/Mirror/Examples/MultipleMatches/Prefabs.meta
  Assets/Mirror/Examples/MultipleMatches/Prefabs/CellGUI.prefab
  Assets/Mirror/Examples/MultipleMatches/Prefabs/CellGUI.prefab.meta
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchController.prefab
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchController.prefab.meta
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchGUI.prefab
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchGUI.prefab.meta
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchPlayer.prefab
  Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchPlayer.prefab.meta
  Assets/Mirror/Examples/MultipleMatches/Prefabs/PlayerGUI.prefab
  Assets/Mirror/Examples/MultipleMatches/Prefabs/PlayerGUI.prefab.meta
  Assets/Mirror/Examples/MultipleMatches/README.md
  Assets/Mirror/Examples/MultipleMatches/README.md.meta
  Assets/Mirror/Examples/MultipleMatches/Scenes.meta
  Assets/Mirror/Examples/MultipleMatches/Scenes/Main.unity
  Assets/Mirror/Examples/MultipleMatches/Scenes/Main.unity.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/CellGUI.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/CellGUI.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchGUI.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchGUI.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchMessages.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchMessages.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchNetworkManager.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchNetworkManager.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/PlayerGUI.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/PlayerGUI.cs.meta
  Assets/Mirror/Examples/MultipleMatches/Scripts/RoomGUI.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/RoomGUI.cs.meta
Labels: PassedTestRoutine, enhancement

#2497 fix(weaver): Weaver finds correct log methods for unity 2020.2
  Assets/Mirror/Editor/Weaver/WeaverTypes.cs
Labels: Awaiting Rreview

#2465 fix: prevent allocation of massive array
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Labels: Awaiting Rreview

#2507 feat: DisallowMultipleComponent on all transports
  Assets/Mirror/Runtime/Transport/FallbackTransport.cs
  Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
  Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs
  Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
  Assets/Mirror/Runtime/Transport/SimpleWebTransport/SimpleWebTransport.cs
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Labels: PassedTestRoutine, enhancement

#2512 Moving FindPath to editor scripts
  Assets/Mirror/Editor/EditorHelper.cs
  Assets/Mirror/Editor/EditorHelper.cs.meta
  Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
  Assets/Mirror/Tests/Editor/Weaver/WeaverAssembler.cs
Labels: Awaiting Rreview
