Repository MirrorNetworking/Mirror, pull requests merged in 2020-02, with the labels that each got.

#1464 feat: Implemented NetworkReaderPool
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkReaderPool.cs
  Assets/Mirror/Runtime/NetworkReaderPool.cs.meta
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1473 Add Header to NetworkBehaviourInspector
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: PassedTestRoutine, enhancement

#1474 Breaking: Renamed localEulerAnglesSensitivity
  Assets/Mirror/Components/NetworkTransformBase.cs
Labels: PassedTestRoutine, enhancement

#1470 fix: weaver support array of custom types
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Tests/Editor/WeaverTest.cs
  Assets/Mirror/Tests/Editor/WeaverTests~/TestingScriptableObjectArraySerialization.cs
Labels: PassedTestRoutine, bug

#1482 BREAKING: Rename NetworkWriter Write<T>to WriteMessage
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
  Assets/Mirror/Tests/Editor/MessageBaseTests.cs
  Assets/Mirror/Tests/Editor/MessageInheritanceTest.cs
Labels: PassedTestRoutine, enhancement

#1480 feat: Added Read<T> Method to NetworkReader
  Assets/Mirror/Runtime/NetworkReader.cs
Labels: PassedTestRoutine, enhancement

#1483 fix #1475: isClient is true in OnDestroy on host/client mode again. Reverts commit d00c95bb55eedceb4f0811de54604c960c9352fe
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine

#1485 feat: Add headless check to Discovery
  Assets/Mirror/Components/Discovery/NetworkDiscovery.cs
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Labels: PassedTestRoutine, enhancement

#1471 feat: supports scriptable objects
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Editor/Weaver/Resolvers.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
  Assets/Mirror/Editor/Weaver/Writers.cs
  Assets/Mirror/Tests/Editor/ScriptableObjectWriterTest.cs
  Assets/Mirror/Tests/Editor/ScriptableObjectWriterTest.cs.meta
  Assets/Mirror/Tests/Editor/WeaverTest.cs
  Assets/Mirror/Tests/Editor/WeaverTests~/SyncVarsDerivedScriptableObject.cs
Labels: enhancement, question, work in progress

#1490 feat: Disposable PooledNetworkReader / PooledNetworkWriter
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkReaderPool.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/NetworkWriterPool.cs
  Assets/Mirror/Tests/Editor/NetworkReaderTest.cs
  Assets/Mirror/Tests/Editor/NetworkWriterPoolTest.cs
  Assets/Mirror/Tests/Editor/NetworkWriterPoolTest.cs.meta
Labels: PassedTestRoutine, enhancement

#1479 feat: Block Play Mode and Builds for Weaver Errors
  Assets/Mirror/Editor/EnterPlayModeSettingsCheck.cs
  Assets/Mirror/Editor/Mirror.Editor.asmdef
  Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
Labels: PassedTestRoutine, enhancement

#1498 fix: Host Player Ready Race Condition
  Assets/Mirror/Runtime/ClientScene.cs
Labels: PassedTestRoutine, bug

#1496 feat: NetworkSceneChecker use Scene instead of string name
  Assets/Mirror/Components/NetworkSceneChecker.cs
Labels: PassedTestRoutine, enhancement

#1500 feat: Check for client authority in CmdClientToServerSync
  Assets/Mirror/Components/NetworkTransformBase.cs
Labels: PassedTestRoutine, enhancement

#1501 feat: Check for client authority in NetworkAnimator Cmd's
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, enhancement

#1504 fix: return & continue on separate line
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
  Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
  Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Client.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Server.cs
  Assets/Mirror/Runtime/Transport/Websocket/Server.cs
  Assets/Mirror/Tests/Editor/WeaverAssembler.cs
Labels: PassedTestRoutine, enhancement

#1509 fix: Add missing channelId to NetworkConnectionToClient.Send calls
  Assets/Mirror/Runtime/NetworkServer.cs
  doc/General/ChangeLog.md
Labels: PassedTestRoutine, bug, regression

#1506 Rearranged StartHost methods
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1510 Remove Redundant Set of mode = Offline
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1512 feat: Cosmetic Enhancement of Network Manager
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1513 Make StartHost Not virtual
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1524 fix: build in IL2CPP
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
Labels: regression
