Repository MirrorNetworking/Mirror, pull requests merged in 2020-01, with the labels that each got.

#1385 Update Example Prefabs & Scenes to Master
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Capsule.prefab
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cube.prefab
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cylinder.prefab
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Sphere.prefab
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Tank.prefab
  Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
  Assets/Mirror/Examples/AdditiveScenes/Scenes/SubScene.unity
  Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
  Assets/Mirror/Examples/Chat/Prefabs/Player.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
  Assets/Mirror/Examples/Pong/Scenes/Scene.unity
  Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
  Assets/Mirror/Examples/Room/Prefabs/RoomPlayer.prefab
  Assets/Mirror/Examples/Room/Scenes/OfflineScene.unity
  Assets/Mirror/Examples/Tanks/Prefabs/Projectile.prefab
  Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
Labels: PassedTestRoutine, enhancement

#1387 Room Example: NetworkManager moved to Offline scene
  Assets/Mirror/Examples/Room/README.md
  Assets/Mirror/Examples/Room/Scenes/OfflineScene.unity
  Assets/Mirror/Examples/Room/Scenes/RoomScene.unity
  Assets/Mirror/Examples/Room/Scripts/OfflineGUI.cs
  Assets/Mirror/Examples/Room/Scripts/OfflineGUI.cs.meta
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement

#1386 fix: Client must wait for scene message before sending AddPlayer message
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: bug, regression

#1406 Remove DDOL escape
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: PassedTestRoutine, bug

#1405 fix: Check clientAuthority in NetworkAnimator
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, bug

#1404 fix: Use hasAuthority instead of isLocalPlayer
  Assets/Mirror/Components/NetworkTransformBase.cs
Labels: PassedTestRoutine, bug

#1408 fix: #1241 - Telepathy updated to latest version. All tests are passing again. Thread.Interrupt was replaced by Abort+Join.
  Assets/Mirror/Runtime/Transport/Telepathy/Client.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Common.cs
  Assets/Mirror/Runtime/Transport/Telepathy/EventType.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Logger.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Message.cs
  Assets/Mirror/Runtime/Transport/Telepathy/NetworkStreamExtensions.cs
  Assets/Mirror/Runtime/Transport/Telepathy/SafeQueue.cs
  Assets/Mirror/Runtime/Transport/Telepathy/Server.cs
  Assets/Mirror/Runtime/Transport/Telepathy/ThreadExtensions.cs
Labels: PassedTestRoutine, enhancement

#1415 fix #1407: Check EnterPlayModeSettings and disable if needed for 2019.3 support
  Assets/Mirror/Editor/EnterPlayModeSettingsCheck.cs
  Assets/Mirror/Editor/EnterPlayModeSettingsCheck.cs.meta
Labels: PassedTestRoutine

#1416 breaking: fix: #1151 - assign SyncVars before calling the Hook. Hook now passes old and new value instead of changing it from new value to old value, as this would break all SyncVar Hook projects silently.
  Assets/Mirror/Components/NetworkRoomPlayer.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/RandomColor.cs
  Assets/Mirror/Examples/Basic/Scripts/Player.cs
  Assets/Mirror/Examples/Room/Scripts/RandomColor.cs
  Assets/Mirror/Tests/WeaverTest.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsDerivedNetworkBehaviour.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsDerivedScriptableObject.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsDifferentModule.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsGenericParam.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsInterface.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsMoreThan63.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsStatic.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsSyncList.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsTooManyHookParams.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsValid.cs
  Assets/Mirror/Tests/WeaverTests~/SyncVarsWrongHookType.cs
  doc/Guides/Sync/SyncVarHook.md
Labels: PassedTestRoutine

#1422 Use NetworkWriterPool in NetworkTransform
  Assets/Mirror/Components/NetworkTransformBase.cs
Labels: PassedTestRoutine, enhancement

#1421 Use NetworkWriterPool in NetworkAnimator
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, enhancement

#1420 feat: Add ResetTrigger to Network Animator
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, enhancement

#1424 feat: NetworkAnimator warns if you use it incorrectly
  Assets/Mirror/Components/NetworkAnimator.cs
  doc/General/ChangeLog.md
Labels: PassedTestRoutine, enhancement

#1426 Network server handlers private
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1409 fix: StopHost with offline scene calls scene change twice
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1425 feat: Add Sensitivity to NetworkTransform
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
  Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
  Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
Labels: PassedTestRoutine, enhancement

#1437 Reordered NetworkTransform Fields w/ Headers
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransformChild.cs
Labels: PassedTestRoutine, enhancement

#1440 fix: Set AllPlayersready false in the Room scene
  Assets/Mirror/Components/NetworkRoomManager.cs
Labels: PassedTestRoutine, bug

#1439 fix: Fix Room Slots for clients
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Components/NetworkRoomPlayer.cs
Labels: PassedTestRoutine, bug

#1443 Updated video tutorial link.
  doc/Guides/Communications/NetworkBehavior.md
Labels: docs

#1448 Added ErrorMessage Test
  Assets/Mirror/Tests/MessageTests.cs
  Assets/Mirror/Tests/MessageTests.cs.meta
Labels: enhancement

#1310 Remove m_sceneId
  Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
  Assets/Mirror/Examples/AdditiveScenes/Scenes/SubScene.unity
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: PassedTestRoutine, enhancement

#1271 feat: Network Scene Checker Component
  Assets/Mirror/Components/NetworkSceneChecker.cs
  Assets/Mirror/Components/NetworkSceneChecker.cs.meta
  doc/Components/NetworkSceneChecker.md
  doc/Components/NetworkSceneChecker.png
  doc/Components/toc.yml
Labels: PassedTestRoutine, enhancement

#1455 fix: Restore Empty NetworkIdentityEditor
  Assets/Mirror/Editor/NetworkIdentityEditor.cs
  Assets/Mirror/Editor/NetworkIdentityEditor.cs.meta
Labels: PassedTestRoutine, bug, regression

#1452 feat: Mirror Icon for all components
  Assets/Mirror/Authenticators/BasicAuthenticator.cs.meta
  Assets/Mirror/Authenticators/TimeoutAuthenticator.cs.meta
  Assets/Mirror/Components/NetworkAnimator.cs.meta
  Assets/Mirror/Components/NetworkLobbyManager.cs.meta
  Assets/Mirror/Components/NetworkLobbyPlayer.cs.meta
  Assets/Mirror/Components/NetworkProximityChecker.cs.meta
  Assets/Mirror/Components/NetworkRoomManager.cs.meta
  Assets/Mirror/Components/NetworkRoomPlayer.cs.meta
  Assets/Mirror/Components/NetworkSceneChecker.cs.meta
  Assets/Mirror/Components/NetworkTransform.cs.meta
  Assets/Mirror/Components/NetworkTransformBase.cs.meta
  Assets/Mirror/Components/NetworkTransformChild.cs.meta
  Assets/Mirror/Icon.meta
  Assets/Mirror/Icon/MirrorIcon.png
  Assets/Mirror/Icon/MirrorIcon.png.meta
  Assets/Mirror/Runtime/NetworkIdentity.cs.meta
  Assets/Mirror/Runtime/NetworkManager.cs.meta
  Assets/Mirror/Runtime/NetworkManagerHUD.cs.meta
  Assets/Mirror/Runtime/NetworkStartPosition.cs.meta
  Assets/Mirror/Runtime/Transport/FallbackTransport.cs.meta
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs.meta
  Assets/Mirror/Runtime/Transport/MultiplexTransport.cs.meta
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs.meta
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs.meta
  doc/General/ChangeLog.md
Labels: PassedTestRoutine, enhancement

#1457 Make the Dictionary public
  Assets/Mirror/Components/NetworkSceneChecker.cs
Labels: PassedTestRoutine, enhancement

#1454 breaking: Transports can now provide their Uri
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/Transport/FallbackTransport.cs
  Assets/Mirror/Runtime/Transport/LLAPITransport.cs
  Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
  Assets/Mirror/Runtime/Transport/Transport.cs
  Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Labels: PassedTestRoutine, enhancement

#1458 fix: Prevent AddPlayer after Additve Scene operation
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1456 Update PreprocessorDefines
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
Labels: PassedTestRoutine, enhancement

#1453 feat: LAN Network discovery
  Assets/Mirror/Components/Discovery.meta
  Assets/Mirror/Components/Discovery/NetworkDiscovery.cs
  Assets/Mirror/Components/Discovery/NetworkDiscovery.cs.meta
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs.meta
  Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs
  Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs.meta
  Assets/Mirror/Components/Discovery/ServerRequest.cs
  Assets/Mirror/Components/Discovery/ServerRequest.cs.meta
  Assets/Mirror/Components/Discovery/ServerResponse.cs
  Assets/Mirror/Components/Discovery/ServerResponse.cs.meta
  Assets/Mirror/Examples/Discovery.meta
  Assets/Mirror/Examples/Discovery/Prefabs.meta
  Assets/Mirror/Examples/Discovery/Prefabs/Player.prefab
  Assets/Mirror/Examples/Discovery/Prefabs/Player.prefab.meta
  Assets/Mirror/Examples/Discovery/Scenes.meta
  Assets/Mirror/Examples/Discovery/Scenes/Scene.unity
  Assets/Mirror/Examples/Discovery/Scenes/Scene.unity.meta
  Assets/Mirror/Runtime/Transport/FallbackTransport.cs
  Assets/ScriptTemplates/56-Mirror__Network Discovery-NewNetworkDiscovery.cs.txt
  Assets/ScriptTemplates/56-Mirror__Network Discovery-NewNetworkDiscovery.cs.txt.meta
  doc/Components/NetworkDiscovery.md
  doc/Components/NetworkDiscovery.png
  doc/Components/index.md
  doc/Components/toc.yml
  doc/General/ChangeLog.md
  doc/General/Deprecations.md
  doc/General/ScriptTemplates.png
  doc/General/ScriptTemplates.zip
  doc/Guides/NetworkDiscovery.md
  doc/Guides/toc.yml
Labels: PassedTestRoutine, enhancement

#1459 BasicAuthenticatorTest
  Assets/Mirror/Tests/Editor/BasicAuthenticatorTest.cs
  Assets/Mirror/Tests/Editor/BasicAuthenticatorTest.cs.meta
Labels: PassedTestRoutine, enhancement

#1463 Message Tests
  Assets/Mirror/Tests/Editor/MessageTests.cs
Labels: PassedTestRoutine, enhancement
