Repository MirrorNetworking/Mirror, pull requests merged in 2020-04, with the labels that each got.

#1611 feat: logging api
  Assets/Mirror/Runtime/LogFactory.cs
  Assets/Mirror/Runtime/LogFactory.cs.meta
  Assets/Mirror/Tests/Editor/LogFactoryTests.cs
  Assets/Mirror/Tests/Editor/LogFactoryTests.cs.meta
Labels: work in progress

#1636 fix: Destroyed NetMan due to singleton collision must not continue.
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1653 adding performance test asmdef
  Assets/Mirror/Runtime/AssemblyInfo.cs
  Assets/Mirror/Tests/Performance.meta
  Assets/Mirror/Tests/Performance/Editor.meta
  Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef
  Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef.meta
  Assets/Mirror/Tests/Performance/Runtime.meta
  Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef
  Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef.meta
  Packages/manifest.json
Labels: work in progress

#1658 fix: Remove Junk Packages
  Packages/manifest.json
Labels: PassedTestRoutine, enhancement

#1662 Benchmark performance test 2 - Idle benchmark
  Assets/Mirror/Examples/Benchmarks/10k/Scripts/Health.cs
  Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs
Labels: work in progress

#1683 fix: Re-enable transport if aborting additive load/unload
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1684 fix: Check SceneManager GetSceneByName and GetSceneByPath
  Assets/Mirror/Examples/AdditiveScenes/Scripts/AdditiveNetworkManager.cs
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1613 Logger editor
  Assets/Mirror/Editor/LogLevelWindow.cs
  Assets/Mirror/Editor/LogLevelWindow.cs.meta
  Assets/Mirror/Runtime/AssemblyInfo.cs
  Assets/Mirror/Runtime/LogFactory.cs
Labels: work in progress

#1681 breaking: NetworkVisbility component
  Assets/Mirror/Components/NetworkProximityChecker.cs
  Assets/Mirror/Components/NetworkSceneChecker.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkVisibility.cs
  Assets/Mirror/Runtime/NetworkVisibility.cs.meta
  Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Labels: work in progress

#1707 feat: Make OnSetHostVisibility virtual with default functionality
  Assets/Mirror/Components/NetworkProximityChecker.cs
  Assets/Mirror/Components/NetworkSceneChecker.cs
  Assets/Mirror/Runtime/NetworkVisibility.cs
Labels: PassedTestRoutine, enhancement

#1716 feat: Added SyncList.Find and SyncList.FindAll
  Assets/Mirror/Runtime/SyncList.cs
  Assets/Mirror/Tests/Editor/SyncListTest.cs
Labels: Needs Unit Test

#1723 fix: Eliminate NetworkAnimator SetTrigger double firing on Host
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, bug

#1709 fix: Don't destroy the player twice
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
  Assets/Mirror/Tests/Runtime/NetworkServerTest.cs.meta
Labels: PassedTestRoutine, bug

#1688 feat: NetworkMatchChecker Component
  Assets/Mirror/Components/NetworkMatchChecker.cs
  Assets/Mirror/Components/NetworkMatchChecker.cs.meta
  Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs
  Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs.meta
  doc/Components/NetworkMatchChecker.md
  doc/Components/NetworkMatchChecker.png
  doc/Components/index.md
Labels: PassedTestRoutine, enhancement

#1739 Using IsDerivedFrom instead of while loop
  Assets/Mirror/Editor/Weaver/Weaver.cs
Labels: PendingTestRoutine

#1751 fix: Remove leftover AddPlayer methods now that extraData is gone
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkManagerHUD.cs
Labels: PassedTestRoutine, bug

#1770 using MemoryTransport to make test more stable
  Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
Labels: enhancement

#1724 feat: Disconnect Dead Clients
  Assets/Mirror/Runtime/LocalConnections.cs
  Assets/Mirror/Runtime/NetworkConnection.cs
  Assets/Mirror/Runtime/NetworkConnectionToClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Common/MemoryTransport.cs
  Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
  doc/Components/NetworkManagerInspector.png
  doc/Components/NetworkRoomManager.png
  doc/General/ChangeLog.md
Labels: Needs Stress Test, PassedTestRoutine, enhancement

#1767 Weaver test for sync list using interface
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListErrorForInterface.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInterfaceWithCustomMethods.cs
Labels: enhancement

#1768 fix: weaver syncLists now checks for SerializeItem in base class
  Assets/Mirror/Editor/Weaver/Extensions.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInheritanceWithOverrides.cs
Labels: enhancement

#1769 adding namespace to runtime tests
  Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs
  Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
  Assets/Mirror/Tests/Runtime/HostSetup.cs
  Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
  Assets/Mirror/Tests/Runtime/NetworkManagerTests.cs
  Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
Labels: enhancement, work in progress

#1778 feat: Allow Multiple Network Animator
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: PassedTestRoutine, enhancement

#1773 feat: NetworkServer.SendToReady
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#1697 feat: Allowing Multiple Concurrent Additive Scenes
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs
  Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs.meta
  Assets/Mirror/Tests/Runtime/Scenes.meta
  Assets/Mirror/Tests/Runtime/Scenes/SceneObjectSpawningTestsScene.unity
  Assets/Mirror/Tests/Runtime/Scenes/SceneObjectSpawningTestsScene.unity.meta
  Assets/Mirror/Tests/Runtime/Scenes/TestNetworkManager.prefab
  Assets/Mirror/Tests/Runtime/Scenes/TestNetworkManager.prefab.meta
  Assets/Mirror/Tests/Runtime/Scenes/TestPlayer.prefab
  Assets/Mirror/Tests/Runtime/Scenes/TestPlayer.prefab.meta
Labels: PassedTestRoutine, enhancement

#1775 feat: Adding ReplaceHandler functions to NetworkServer and NetworkClient
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, enhancement

#1805 fixing error message
  Assets/Mirror/Runtime/LogFactory.cs
Labels: PassedTestRoutine, enhancement

#1820 fix: fixing syncmode not showing up in Inspector
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: PassedTestRoutine, bug
