Repository MirrorNetworking/Mirror, pull requests merged in 2020-05, with the labels that each got.

#1829 fix: clear all message handlers on Shutdown
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: PassedTestRoutine, bug

#1836 adding enabled check to loops
  Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Labels: bug, regression

#1772 feat: Add NetworkServer.RemovePlayerForConnection
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
Labels: PassedTestRoutine, enhancement

#1686 feat: Multiple Concurrent Additive Physics Scenes Example
  Assets/Mirror/Examples/MultipleAdditiveScenes.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/Icosphere.physicMaterial
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/Icosphere.physicMaterial.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/Player.physicMaterial
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/Player.physicMaterial.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/RoomBounce.physicMaterial
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Physics/RoomBounce.physicMaterial.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/PlayArea.mat
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/PlayArea.mat.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/Player.mat
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/Player.mat.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/Prize.mat
  Assets/Mirror/Examples/MultipleAdditiveScenes/Materials/Render/Prize.mat.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere/Icosphere.obj
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere/Icosphere.obj.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere/Materials.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere/Materials/Icosphere.mat
  Assets/Mirror/Examples/MultipleAdditiveScenes/Models/Icosphere/Materials/Icosphere.mat.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Icosphere.prefab
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Icosphere.prefab.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Player.prefab.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Prize.prefab
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Prize.prefab.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/README.md
  Assets/Mirror/Examples/MultipleAdditiveScenes/README.md.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Game.unity
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Game.unity.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Main.unity
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Main.unity.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsCollision.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsCollision.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsSimulator.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsSimulator.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerController.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerController.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerScore.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerScore.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/RandomColor.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/RandomColor.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs.meta
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Spawner.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Spawner.cs.meta
Labels: PassedTestRoutine, enhancement

#1842 fix: Don't call RegisterClientMessages twice
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1835 breaking: Eliminates RemovePlayerMessage As Security Risk
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/ClientScene.cs
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Labels: PassedTestRoutine, bug

#1803 Stopping logger error causing weaver tests to fail
  Assets/Mirror/Tests/Editor/Weaver/WeaverTests.cs
Labels: enhancement

#1804 adding assert extension method
  Assets/Mirror/Runtime/Logging/LogFactory.cs
Labels: enhancement

#1864 fix: Cleaning up network objects when server stops
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: Needs Stress Test, bug, work in progress

#1861 add logger to all classes that have logging but no logger
  Assets/Mirror/Authenticators/BasicAuthenticator.cs
  Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
  Assets/Mirror/Components/NetworkAnimator.cs
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Components/NetworkRoomPlayer.cs
  Assets/Mirror/Components/NetworkSceneChecker.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/AdditiveNetworkManager.cs
  Assets/Mirror/Examples/AdditiveScenes/Scripts/ZoneHandler.cs
  Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
  Assets/Mirror/Examples/ListServer/ListServer.cs
  Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs
  Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
  Assets/Mirror/Examples/Room/Scripts/Reward.cs
  Assets/Mirror/Runtime/LocalConnections.cs
  Assets/Mirror/Runtime/MessagePacker.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkReaderPool.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/NetworkTime.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
  Assets/Mirror/Runtime/NetworkWriterPool.cs
Labels: enhancement, question, work in progress

#1885 feat: Improved Log Settings Window Appearance
  Assets/Mirror/Editor/Logging/LogLevelWindow.cs
  Assets/Mirror/Editor/Logging/LogLevelsGUI.cs
Labels: PassedTestRoutine, enhancement

#1865 fix: Don't call RegisterClientMessages every scene change
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, bug

#1899 fix: showing sync settings for non visible syncvar
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: PassedTestRoutine, bug

#1914 feat: Use SortedDictionary for LogSettings
  Assets/Mirror/Runtime/Logging/LogFactory.cs
  Assets/Mirror/Runtime/Logging/LogSettings.cs
Labels: PassedTestRoutine, enhancement

#1906 Gamify Tanks Example
  Assets/Mirror/Examples/Tanks/Prefabs/Projectile.prefab
  Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
  Assets/Mirror/Examples/Tanks/Scenes/Scene.unity
  Assets/Mirror/Examples/Tanks/Scripts/Projectile.cs
  Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
  Assets/Mirror/Examples/Tanks/Scripts/TanksNetworkManager.cs
  Assets/Mirror/Examples/Tanks/Scripts/TanksNetworkManager.cs.meta
Labels: enhancement

#1921 feat: adding OnRoomServerPlayersNotReady to NetworkRoomManager that is called when player ready changes and atleast 1 player is not ready
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/ScriptTemplates/54-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt
  doc/General/ChangeLog.md
Labels: PassedTestRoutine, enhancement

#1918 feat: Adding ignoreAuthority Option to Command
  Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Runtime/CustomAttributes.cs
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Editor/CommandAttrributeTest.cs
  Assets/Mirror/Tests/Editor/CommandAttrributeTest.cs.meta
  Assets/Mirror/Tests/Editor/CustomAttrributeTest.cs
  Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
  Assets/Mirror/Tests/Editor/NetworkServerTest.cs
  Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
  Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandThatIgnoresAuthority.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandValid.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandWithArguments.cs
Labels: PassedTestRoutine, enhancement
