Repository MirrorNetworking/Mirror, pull requests merged in 2021-03, with the labels that each got.

#2616 fix: NetworkIdentity.isLocalPlayer is only set, but never reset. fixes a bug where isLocalPlayer would be false in OnDestroy, so some components couldn't rely on it in OnDestroy. fixes #2615 (this is also faster than comparing ClientScene.localPlayer each time)
  Assets/Mirror/Runtime/NetworkIdentity.cs
Labels: work in progress

#2580 feat: Added bool to Discovery to disable automatic active discovery
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Labels: PassedTestRoutine, enhancement

#2659 breaking: Compiler symbols culled to Mirror 17 and later.
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  ProjectSettings/ProjectSettings.asset
Labels: PassedTestRoutine, enhancement

#2661 Updated examples to not sync scale
  Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/Benchmark/Prefabs/Monster.prefab
  Assets/Mirror/Examples/Benchmark/Prefabs/Player.prefab
  Assets/Mirror/Examples/Cloud/PongWithListServer/Prefabs/Ball.prefab
  Assets/Mirror/Examples/Cloud/PongWithListServer/Prefabs/Racket.prefab
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Icosphere.prefab
  Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Player.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
  Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
  Assets/Mirror/Examples/RigidbodyPhysics/Scenes/BounceScene.unity
  Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
Labels: PassedTestRoutine, enhancement

#2666 fix: Prevent client shutdown from running twice
  Assets/Mirror/Runtime/NetworkClient.cs
Labels: PassedTestRoutine, bug, regression

#2660 feat: Call ConfigureServerFrameRate For Headless Clients
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: PassedTestRoutine, enhancement
