Repository MirrorNetworking/Mirror, pull requests merged in 2021-08, with the labels that each got.

#2863 Improved NetworkIdentity.Reset test
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Labels: Awaiting Rreview, enhancement

#2870 fix: Raise OnDisconnectedEvent before changing ConnectState
  Assets/Mirror/Runtime/NetworkClient.cs
Labels: bug, Awaiting Rreview

#2843 Simplify NetworkManager.isNetworkActive
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
Labels: enhancement, Awaiting Rreview

#2875 Defines for OnGUI
  Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
  Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Labels: enhancement, Awaiting Rrrrreview

#2876 fix: NT Base OnDrawGizmos only when playing
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
Labels: bug, regression, Awaiting Rrrrreview

#2856 fix: Fix delayed movement in client authority mode
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
Labels: bug, Awaiting Rrrrreview
