Repository MirrorNetworking/Mirror, pull requests merged in 2021-10, with the labels that each got.

#2953 fix: Prevent StopClient from running twice
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: bug, regression, Awaiting Review

#2951 feature: SyncVar<T>
  Assets/Mirror/Editor/SyncVarDrawer.cs
  Assets/Mirror/Editor/SyncVarDrawer.cs.meta
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/SyncVar.cs
  Assets/Mirror/Runtime/SyncVar.cs.meta
  Assets/Mirror/Runtime/SyncVarGameObject.cs
  Assets/Mirror/Runtime/SyncVarGameObject.cs.meta
  Assets/Mirror/Runtime/SyncVarNetworkBehaviour.cs
  Assets/Mirror/Runtime/SyncVarNetworkBehaviour.cs.meta
  Assets/Mirror/Runtime/SyncVarNetworkIdentity.cs
  Assets/Mirror/Runtime/SyncVarNetworkIdentity.cs.meta
  Assets/Mirror/Runtime/Utils.cs
  Assets/Mirror/Tests/Editor/SyncVarGameObjectTests.cs
  Assets/Mirror/Tests/Editor/SyncVarGameObjectTests.cs.meta
  Assets/Mirror/Tests/Editor/SyncVarNetworkBehaviourAbstractTests.cs
  Assets/Mirror/Tests/Editor/SyncVarNetworkBehaviourAbstractTests.cs.meta
  Assets/Mirror/Tests/Editor/SyncVarNetworkBehaviourInheritedTests.cs
  Assets/Mirror/Tests/Editor/SyncVarNetworkBehaviourInheritedTests.cs.meta
  Assets/Mirror/Tests/Editor/SyncVarNetworkIdentityTests.cs
  Assets/Mirror/Tests/Editor/SyncVarNetworkIdentityTests.cs.meta
  Assets/Mirror/Tests/Editor/SyncVarTests.cs
  Assets/Mirror/Tests/Editor/SyncVarTests.cs.meta
Labels: Weaver, 2020

#2982 fix: Check NetworkServer.active in DestroyObject
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: bug, Awaiting Review

#2981 fix: Added HashSet for disconnecting connections
  Assets/Mirror/Authenticators/BasicAuthenticator.cs
Labels: bug, work in progress
