Repository MirrorNetworking/Mirror, pull requests merged in 2021-05, with the labels that each got.

#2713 fix: Reset Network Time whenever server starts
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/NetworkTime.cs
Labels: PassedTestRoutine, bug

#2736 fix: Shutdown Discovery in OnDisable / OnDestroy
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Labels: PassedTestRoutine, bug

#2700 fix: fixing NetworkDiagnostics receive for batching
  Assets/Mirror/Runtime/MessagePacking.cs
Labels: PassedTestRoutine, bug, regression

#2742 breaking: NetworkBehaviour .netIdentity, .ComponentIndex, .NetworkBehaviours[] simplified by setting it from NetworkIdentity.Awake()
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Labels: PassedTestRoutine
