Repository MirrorNetworking/Mirror, pull requests merged in 2021-12, with the labels that each got.

#3008 feat: Added Reset to Interest Management
  Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
  Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
  Assets/Mirror/Runtime/InterestManagement.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/ScriptTemplates/53-Mirror__Custom Interest Management-CustomInterestManagement.cs.txt
Labels: enhancement, Awaiting Review

#3009 fix: Suppress Commands When Not Ready
  Assets/Mirror/Runtime/NetworkBehaviour.cs
Labels: enhancement, Awaiting Review

#3011 Suppress Cmds when conn not ready
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement, Awaiting Review

#3013 fix: onlySendOnMove for new NetworkTransform
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
Labels: enhancement, regression, Awaiting Review

#3016 fix: Websocket Transport: ignore headers case when checking handshake key
  Assets/Mirror/Runtime/Transport/SimpleWebTransport/Client/StandAlone/ClientHandshake.cs
Labels: bug, Awaiting Review

#3020 fix: Explicit types for default nullables
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Labels: bug, regression, Awaiting Review

#2820 fix: Obsolete NetworkConnection param in client callbacks
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Examples/AdditiveLevels/Scripts/AdditiveLevelsNetworkManager.cs
  Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchNetworkManager.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Labels: enhancement, Awaiting Review

#3027 breaking: NetworkAuthenticator OnClientAuthenticated Changed
  Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
  Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
  Assets/Mirror/Runtime/NetworkAuthenticator.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, Breaking Change, Awaiting Review

#3026 fix: Transport default channel = Reliable
  Assets/Mirror/Runtime/Transport/Transport.cs
Labels: enhancement, Awaiting Review

#3028 feat: Support Fast Enter Playmode
  Assets/Mirror/Editor/Empty/EnterPlayModeSettingsCheck.cs
  Assets/Mirror/Editor/Empty/EnterPlayModeSettingsCheck.cs.meta
  Assets/Mirror/Editor/EnterPlayModeSettingsCheck.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkDiagnostics.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkLoop.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/NetworkTime.cs
  Assets/Mirror/Tests/Editor/NetworkClientTests.cs
  Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
  Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Labels: enhancement, Awaiting Review

#3033 fix: Use IsNullOrWhiteSpace instead of IsNullOrEmpty
  Assets/Mirror/Components/InterestManagement/Team/TeamInterestManagement.cs
  Assets/Mirror/Components/NetworkRoomManager.cs
  Assets/Mirror/Editor/EditorHelper.cs
  Assets/Mirror/Editor/NetworkInformationPreview.cs
  Assets/Mirror/Editor/SceneDrawer.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/Transport/SimpleWebTransport/Server/ServerHandshake.cs
  Assets/Mirror/Runtime/Transport/SimpleWebTransport/SslConfigLoader.cs
Labels: enhancement, Awaiting Review

#3034 feat: Support for Texture2D & Sprite
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
Labels: enhancement, Awaiting Review
