Repository MirrorNetworking/Mirror, pull requests merged in 2021-09, with the labels that each got.

#2927 fix: Clear hasAuthority when Unspawning
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Labels: bug, Awaiting Review

#2923 perf: NetworkServer.Broadcast O(N) spawned iteration removed. dirty bits for spawned without observers are now cleared when adding the first observer instead
  Assets/Mirror/Runtime/NetworkBehaviour.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Editor/NetworkBehaviourDirtyBitsTests.cs
  Assets/Mirror/Tests/Editor/NetworkBehaviourSerializeTest.cs
  Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
Labels: work in progress

#2931 fix: Obsolete SyncObject Flush method
  Assets/Mirror/Runtime/SyncDictionary.cs
  Assets/Mirror/Runtime/SyncList.cs
  Assets/Mirror/Runtime/SyncObject.cs
  Assets/Mirror/Runtime/SyncSet.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests~/SyncVarsSyncList.cs
Labels: bug, regression, Awaiting Review

#2924 feat: Implemented ChangeOwnerMessage
  Assets/Mirror/Runtime/Messages.cs
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkIdentity.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Labels: enhancement, Awaiting Review

#2934 fix: Eliminate potential errors in MatchInterestMgmt
  Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
Labels: bug, regression

#2936 Force Network Manager to scene root if DDOL
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: enhancement, Awaiting Review

#2942 Make NetworkConnection.observing public
  Assets/Mirror/Runtime/NetworkConnection.cs
Labels: enhancement, Awaiting Review
