Repository MirrorNetworking/Mirror, pull requests merged in 2021-07, with the labels that each got.

#2758 feat: Add OnSpawned/OnDestroyed events to interest management
  Assets/Mirror/Runtime/InterestManagement.cs
  Assets/Mirror/Runtime/NetworkServer.cs
Labels: enhancement

#2832 fix: Reset lastPingTime
  Assets/Mirror/Runtime/NetworkTime.cs
Labels: Awaiting Rreview, bug

#2833 fix: Prevent recursion overflow when stopping
  Assets/Mirror/Runtime/NetworkManager.cs
Labels: Awaiting Rreview, bug

#2835 feat: Transport Exception Handling
  Assets/Mirror/Runtime/NetworkClient.cs
  Assets/Mirror/Runtime/NetworkManager.cs
  Assets/Mirror/Runtime/NetworkServer.cs
  Assets/Mirror/Runtime/Transport/Transport.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Labels: Awaiting Rreview, enhancement

#2791 feature: NetworkTransform V2 - Snapshot Interpolation
  Assets/Mirror/Components/NetworkTransform.cs
  Assets/Mirror/Components/NetworkTransform2k.meta
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransform.cs
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransform.cs.meta
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs.meta
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformChild.cs
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformChild.cs.meta
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformSnapshot.cs
  Assets/Mirror/Components/NetworkTransform2k/NetworkTransformSnapshot.cs.meta
  Assets/Mirror/Components/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransformChild.cs
  Assets/Mirror/Examples/Benchmark/Prefabs/Monster.prefab
  Assets/Mirror/Examples/Benchmark/Prefabs/Player.prefab
  Assets/Mirror/Runtime/NetworkReader.cs
  Assets/Mirror/Runtime/NetworkWriter.cs
  Assets/Mirror/Runtime/Utils.cs
  Assets/Mirror/Tests/Editor/NetworkTransform2kTests.cs
  Assets/Mirror/Tests/Editor/NetworkTransform2kTests.cs.meta
  Assets/Mirror/Tests/Editor/NetworkTransformTest.cs
  Assets/Mirror/Tests/Editor/SnapshotInterpolationTests.cs
  Assets/Mirror/Tests/Editor/UtilsTests.cs
Labels: enhancement

#2808 Allow reader generation of abstract NetworkBehaviours by reordering checks in Readers.GenerateReader()
  Assets/Mirror/Editor/Weaver/Readers.cs
  Assets/Mirror/Tests/Editor/ClientRpcTest.cs
  Assets/Mirror/Tests/Editor/SyncVarTest.cs
Labels: Needs Unit Test
