Repository MirrorNetworking/Mirror, pull requests merged in 2022-12, with the labels that each got.

#3310 Fixed server and client connection attempt with AddPlayer before authentication completes
  Assets/Mirror/Core/NetworkManager.cs
Labels: work in progress, Needs Research

#3322 NetworkTransformBase - make snapshot lists readonly
  Assets/Mirror/Components/NetworkTransformBase.cs
Labels: Awaiting Review

#3333 feat: NetManHUD StopClient button for Host
  Assets/Mirror/Core/NetworkManagerHUD.cs
Labels: enhancement, Awaiting Review

#3332 Use TryGetComponent
  Assets/Mirror/Core/NetworkBehaviour.cs
  Assets/Mirror/Core/NetworkManager.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/Mirror/Core/NetworkWriterExtensions.cs
Labels: enhancement, Awaiting Review

#3331 NetworkClient - Use TryGetComponent
  Assets/Mirror/Core/NetworkClient.cs
Labels: enhancement, Awaiting Review
