Repository MirrorNetworking/Mirror, pull requests merged in 2023-11, with the labels that each got.

#3645 fix(EdgegapWindow): Simplify clearing ProgressBar
  Assets/Mirror/Hosting/Edgegap/Editor/EdgegapWindow.cs
Labels: Awaiting Review

#3649 fix(PredictedState): Remove public accessors
  Assets/Mirror/Core/Prediction/Prediction.cs
Labels: bug, Awaiting Review

#3648 feat: [SimpleWebTransport] Add ability to specify a custom client port (for reverse proxy scenarios not using port 80/443)
  Assets/Mirror/Transports/SimpleWeb/Editor.meta
  Assets/Mirror/Transports/SimpleWeb/Editor/ClientWebsocketSettingsDrawer.cs
  Assets/Mirror/Transports/SimpleWeb/Editor/ClientWebsocketSettingsDrawer.cs.meta
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/ClientWebsocketSettings.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/ClientWebsocketSettings.cs.meta
  Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
Labels: enhancement, work in progress

#3659 feat(HUD): Better HUD for WebGL
  Assets/Mirror/Core/NetworkManagerHUD.cs
Labels: enhancement, Awaiting Review

#3663 feat(SWT): Logging System Overhaul
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/SimpleWebClient.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/ClientHandshake.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/ClientSslHelper.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/WebSocketClientStandAlone.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/Webgl/WebSocketClientWebGl.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/BufferPool.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Connection.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Log.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/ReadHelper.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/ReceiveLoop.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/SendLoop.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/ServerHandshake.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/ServerSslHelper.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/SimpleWebServer.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/WebSocketServer.cs
  Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
Labels: enhancement, work in progress

#3671 fix(KCP): Use Log.Info instead of Debug.Log
  Assets/Mirror/Transports/KCP/KcpTransport.cs
  Assets/Mirror/Transports/KCP/ThreadedKcpTransport.cs
Labels: enhancement, Awaiting Review

#3669 fix(Telepathy): Shorter Simpler ToString
  Assets/Mirror/Transports/Telepathy/TelepathyTransport.cs
Labels: enhancement, Awaiting Review

#3664 feat(NetworkManager): Refactor Headless Start
  Assets/Mirror/Core/NetworkManager.cs
Labels: enhancement, Awaiting Review

#3670 fix(NetworkManager): Remove check for editor in Start
  Assets/Mirror/Core/NetworkManager.cs
Labels: bug, Awaiting Review
