Repository MirrorNetworking/Mirror, pull requests merged in 2023-12, with the labels that each got.

#3667 fix(Telepathy): Use compiler symbols in Available
  Assets/Mirror/Transports/Telepathy/TelepathyTransport.cs
Labels: enhancement, Awaiting Review

#3668 fix(KCP): Use compiler symbols in Available
  Assets/Mirror/Transports/KCP/KcpTransport.cs
  Assets/Mirror/Transports/KCP/ThreadedKcpTransport.cs
Labels: enhancement, Awaiting Review

#3683 fix(KCP): Added port to ToString
  Assets/Mirror/Transports/KCP/KcpTransport.cs
  Assets/Mirror/Transports/KCP/ThreadedKcpTransport.cs
Labels: enhancement, Awaiting Review

#3693 fix(ConnectionQuality): Move Connection Quality to Network Client
  Assets/Mirror/Core/ConnectionQuality.cs
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkManager.cs
  Assets/ScriptTemplates/51-Mirror__Network Manager With Actions-NewNetworkManagerWithActions.cs.txt
Labels: enhancement, Awaiting Review

#3694 feat(NetworkManager): Ability to toggle auto-start in Editor
  Assets/Mirror/Core/NetworkManager.cs
Labels: enhancement, Awaiting Review

#3615 perf: SyncVar hook invocations no longer instantiate a new action delegate on every call
  Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
Labels: bug, Awaiting Review

#3662 feat(HUD): Support for MultiplexTransport Port
  Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs
Labels: enhancement, Awaiting Review

#3706 fix(NT Base): Consolidate NT fields to NT Base
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Labels: enhancement
