Repository MirrorNetworking/Mirror, pull requests merged in 2024-11, with the labels that each got.

#3937 feat: NetworkTransformHybrid - Hybrid Sync Part 1
  Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid2022.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid2022.cs.meta
Labels: enhancement, work in progress

#3946 fix(PredictionUtils): move freeze rotation before constraints
  Assets/Mirror/Components/PredictedRigidbody/PredictionUtils.cs
Labels: bug, Awaiting Review

#3948 fix(NetworkTransformHybrid) Default SyncDir to ClientToServer
  Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
Labels: enhancement, Awaiting Review

#3929 fix(NetworkDiscoveryHUD): More robust OnValidate / Reset
  Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
  Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs
  Assets/Mirror/Examples/Discovery/Scenes/MirrorDiscovery.unity
Labels: bug, Awaiting Review

#3949 fix(InterestManagementBase): Improve SetHostVisibility
  Assets/Mirror/Core/InterestManagementBase.cs
Labels: enhancement, Awaiting Review
