Repository MirrorNetworking/Mirror, pull requests merged in 2024-04, with the labels that each got.

#3788 fix(NetworkRigidbody Components): Added missing OnTeleport overrides
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable.cs
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable2D.cs
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable.cs
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable2D.cs
Labels: Awaiting Review

#3801 fix(NetworkAnimator): Default animatorSpeed to 1
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: bug, Awaiting Review

#3805 feat(MoveToAssetsFolder): Editor Script Moves ScriptTemplates to Assets
  Assets/ScriptTemplates/Editor.meta
  Assets/ScriptTemplates/Editor/MoveToAssetsFolder.cs
  Assets/ScriptTemplates/Editor/MoveToAssetsFolder.cs.meta
Labels: enhancement, Awaiting Review

#3461 feat(Transport): Reimplement Transport Exception Actions
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkManager.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/Mirror/Core/Transport.cs
  Assets/Mirror/Tests/Editor/NetworkClient/NetworkClientTests.cs
  Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
  Assets/Mirror/Tests/Editor/Transports/MiddlewareTransportTest.cs
  Assets/Mirror/Transports/Latency/LatencySimulation.cs
  Assets/Mirror/Transports/Middleware/MiddlewareTransport.cs
  Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs
  Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
  Assets/ScriptTemplates/51-Mirror__Network Manager With Actions-NewNetworkManagerWithActions.cs.txt
Labels: enhancement, Awaiting Review

#3751 breaking(NetworkTransform): Use Flags enum for Sync and Interpolation
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Tests/Editor/NetworkTransform/NetworkTransform2kTests.cs
Labels: enhancement, Awaiting Review

#3808 fix(SyncObjectCollectionField): Pretty SyncCollection Name
  Assets/Mirror/Editor/SyncObjectCollectionsDrawer.cs
Labels: enhancement, Awaiting Review

#3809 fix(NetworkServer): Spawn for owner client even when Force Hidden
  Assets/Mirror/Core/NetworkServer.cs
Labels: bug, Awaiting Review
