Repository MirrorNetworking/Mirror, pull requests merged in 2024-01, with the labels that each got.

#3707 perf(Match Interest Mgmt): Complete Overhaul
  Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
  Assets/Mirror/Components/InterestManagement/Match/NetworkMatch.cs
Labels: enhancement, Awaiting Review

#3715 fix(NetworkManager): No Auth Required for NotReadyMessage
  Assets/Mirror/Core/NetworkManager.cs
Labels: bug, Awaiting Review

#3716 perf(NetworkAnimator): ClientRpc includeOwner False
  Assets/Mirror/Components/NetworkAnimator.cs
Labels: enhancement, Awaiting Review

#3723 fix(Multiplexer): Avoid KeyNotFoundException in OriginalId
  Assets/Mirror/Tests/Editor/Transports/MultiplexTransportTest.cs
  Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs
Labels: bug, Awaiting Review

#3728 feat(NetworkClient): Add RegisterHandler with ChannelId
  Assets/Mirror/Core/NetworkClient.cs
Labels: enhancement, Awaiting Review

#3725 fix: NT-Unreliable Quaternion Compression Fix
  Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Labels: bug, regression, Awaiting Review

#3729 fix(NetworkManager): Prevent client from calling ServerChangeScene
  Assets/Mirror/Core/NetworkManager.cs
Labels: enhancement, Awaiting Review

#3731 fix(Weaver): Move InvokeRpcPrefix from Weaver to RemoteProcedureCalls
  Assets/Mirror/Core/RemoteCalls.cs
  Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
  Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeAccessReplacer.cs
  Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
  Assets/Mirror/Editor/Weaver/Weaver.cs
Labels: enhancement, Awaiting Review

#3727 fix(NetworkServer): Improve Warnings
  Assets/Mirror/Core/NetworkServer.cs
Labels: enhancement, Awaiting Review

#3737 fix: NetworkServer and NetworkClient respect exceptionDisconnect
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkServer.cs
Labels: bug, Awaiting Review

#3742 fix(NetworkIdentity): Separate ResetState
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkIdentity.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentitySerializationTests.cs
  Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentityTests.cs
Labels: enhancement, Awaiting Review

#3743 fix(InterestManagement): Separate ResetState
  Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
  Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
  Assets/Mirror/Core/InterestManagementBase.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/ScriptTemplates/54-Mirror__Custom Interest Management-CustomInterestManagement.cs.txt
Labels: enhancement, Awaiting Review

#3741 feat(NetworkTransform): Default Sync Direction = Client To Server
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Tests/Editor/NetworkTransform/NetworkTransform2kTests.cs
Labels: enhancement, Awaiting Review

#3747 feat(NetworkClient): Add ReplaceHandler with channel param
  Assets/Mirror/Core/NetworkClient.cs
Labels: enhancement, Awaiting Review

#3748 breaking(NetworkIdentity): Rename visible to visibility
  Assets/Mirror/Core/InterestManagement.cs
  Assets/Mirror/Core/NetworkIdentity.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/Mirror/Tests/Editor/InterestManagement/InterestManagementTests_Default.cs
  Assets/Mirror/Tests/Editor/InterestManagement/InterestManagementTests_Distance.cs
  Assets/Mirror/Tests/Editor/InterestManagement/InterestManagementTests_SpatialHashing.cs
Labels: Breaking Change, Awaiting Review

#3750 feat(SyncVar): Arrays are supported
  Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests_IsSuccess/SyncVarsCanBeArray.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests_IsSuccess/SyncVarsCanBeArray.cs.meta
Labels: enhancement, Awaiting Review

#3758 fix(MultiplexTransport): Use TryGetValue for Lookups
  Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs
Labels: bug, Awaiting Review
