Repository MirrorNetworking/Mirror, pull requests merged in 2024-09, with the labels that each got.

#3895 breaking: NetworkTransform sendIntervalMultiplier replaced by syncInterval math
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Labels: work in progress

#3820 feat: Unity 6 Compatibility
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable2D.cs
  Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable2D.cs
  Assets/Mirror/Components/PredictedRigidbody/PredictedRigidbody.cs
  Assets/Mirror/Components/PredictedRigidbody/PredictionUtils.cs
  Assets/Mirror/Examples/BilliardsPredicted/Ball/Pockets.cs
  Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayer.cs
  Assets/Mirror/Examples/Pong/Scripts/Ball.cs
  Assets/Mirror/Examples/Pong/Scripts/Player.cs
Labels: enhancement, Awaiting Review

#3900 breaking: Removed old obsoletes
  Assets/Mirror/Components/Experimental.meta
  Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs
  Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs.meta
  Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
  Assets/Mirror/Components/Experimental/NetworkRigidbody.cs.meta
  Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs
  Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs.meta
  Assets/Mirror/Components/NetworkTransform/NetworkTransform.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransform.cs.meta
  Assets/Mirror/Components/NetworkTransform/NetworkTransformChild.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformChild.cs.meta
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkIdentity.cs
  Assets/Mirror/Core/NetworkManager.cs
  Assets/Mirror/Core/NetworkReaderPooled.cs
  Assets/Mirror/Core/NetworkWriterPooled.cs
  Assets/Mirror/Core/SyncDictionary.cs
  Assets/Mirror/Core/SyncList.cs
  Assets/Mirror/Core/SyncSet.cs
  Assets/Mirror/Core/Threading/ConcurrentNetworkWriterPooled.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
  Assets/Mirror/Tests/Editor/SyncCollections/SyncDictionaryTest.cs
  Assets/Mirror/Tests/Editor/SyncCollections/SyncListStructTest.cs
  Assets/Mirror/Tests/Editor/SyncCollections/SyncListTest.cs
  Assets/Mirror/Tests/Editor/SyncCollections/SyncSetTest.cs
Labels: Breaking Change, Awaiting Review

#3897 feat: Ping/Traffic/FPS Graphs
  .editorconfig
  Assets/Mirror/Components/Profiling.meta
  Assets/Mirror/Components/Profiling/BaseUIGraph.cs
  Assets/Mirror/Components/Profiling/BaseUIGraph.cs.meta
  Assets/Mirror/Components/Profiling/FpsMinMaxAvgGraph.cs
  Assets/Mirror/Components/Profiling/FpsMinMaxAvgGraph.cs.meta
  Assets/Mirror/Components/Profiling/LineGraph.mat
  Assets/Mirror/Components/Profiling/LineGraph.mat.meta
  Assets/Mirror/Components/Profiling/NetworkGraphLines.shader
  Assets/Mirror/Components/Profiling/NetworkGraphLines.shader.meta
  Assets/Mirror/Components/Profiling/NetworkGraphStacked.shader
  Assets/Mirror/Components/Profiling/NetworkGraphStacked.shader.meta
  Assets/Mirror/Components/Profiling/NetworkPingGraph.cs
  Assets/Mirror/Components/Profiling/NetworkPingGraph.cs.meta
  Assets/Mirror/Components/Profiling/NetworkRuntimeProfiler.cs
  Assets/Mirror/Components/Profiling/NetworkRuntimeProfiler.cs.meta
  Assets/Mirror/Components/Profiling/NetworkUsageGraph.cs
  Assets/Mirror/Components/Profiling/NetworkUsageGraph.cs.meta
  Assets/Mirror/Components/Profiling/Prefabs.meta
  Assets/Mirror/Components/Profiling/Prefabs/FPSMinMaxAvg.prefab
  Assets/Mirror/Components/Profiling/Prefabs/FPSMinMaxAvg.prefab.meta
  Assets/Mirror/Components/Profiling/Prefabs/GraphCanvas.prefab
  Assets/Mirror/Components/Profiling/Prefabs/GraphCanvas.prefab.meta
  Assets/Mirror/Components/Profiling/Prefabs/NetworkGraph.prefab
  Assets/Mirror/Components/Profiling/Prefabs/NetworkGraph.prefab.meta
  Assets/Mirror/Components/Profiling/Prefabs/PingGraph.prefab
  Assets/Mirror/Components/Profiling/Prefabs/PingGraph.prefab.meta
  Assets/Mirror/Components/Profiling/StackedGraph.mat
  Assets/Mirror/Components/Profiling/StackedGraph.mat.meta
  Assets/Mirror/Components/Profiling/ToggleHotkey.cs
  Assets/Mirror/Components/Profiling/ToggleHotkey.cs.meta
Labels: enhancement, Awaiting Review
