Repository MirrorNetworking/Mirror, pull requests merged in 2024-02, with the labels that each got.

#3686 fix: fixing time not being sent on connect
  Assets/Mirror/Core/NetworkClient.cs
Labels: bug, Awaiting Review

#3721 feat: NT-UR bit flag changed detection to lower bandwidth usage.
  Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
  Assets/Mirror/Components/NetworkTransform/TransformSyncData.cs
  Assets/Mirror/Components/NetworkTransform/TransformSyncData.cs.meta
Labels: enhancement, Awaiting Review

#3759 fix(NetworkManager): FinishStartHost-Don't force localhost
  Assets/Mirror/Core/NetworkManager.cs
Labels: Awaiting Review

#3765 fix: Safer version for FindAnyObjectByType
  Assets/Mirror/Examples/BilliardsPredicted/Player/PlayerPredicted.cs
  Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerControllerScript.cs
  Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerEmpty.cs
  Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayer.cs
  Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayerManager.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
  Assets/Mirror/Examples/MultipleMatches/Scripts/MatchGUI.cs
  Assets/Mirror/Examples/_Common/Scripts/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs
Labels: bug, regression, Awaiting Review
