Repository MirrorNetworking/Mirror, pull requests merged in 2025-04, with the labels that each got.

#4005 fix(InterestManagementBase): Hide Canvas in SetHostVisibility
  Assets/Mirror/Core/InterestManagementBase.cs
Labels: Awaiting Review

#4008 fix(NetworkManager): Unsubscribe from OnSceneLoaded in OnDestroy
  Assets/Mirror/Core/NetworkManager.cs
Labels: Awaiting Review

#4001 feat: Bool to skip password and auth check in RemoteStatistics.cs
  Assets/Mirror/Components/RemoteStatistics.cs
Labels: Awaiting Review

#4012 feat(NetworkTransform): Update/FixedUpdate/LateUpdate Enum
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
  Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerHybrid.prefab
  Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerReliable.prefab
  Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerUnreliable.prefab
  Assets/Mirror/Examples/PlayerTest/PlayerTestScene.unity
  Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBHybrid.prefab
  Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBReliable.prefab
  Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBUnreliable.prefab
  Assets/Mirror/Examples/PlayerTest/Tank/TankHybrid.prefab
  Assets/Mirror/Examples/PlayerTest/Tank/TankReliable.prefab
  Assets/Mirror/Examples/PlayerTest/Tank/TankUnreliable.prefab
  Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBHybrid.cs
  Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBReliable.cs
  Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBUnreliable.cs
Labels: enhancement, Awaiting Review

#4014 fix(Network Transform): consolidate pendingSnapshot to Base
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
  Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Labels: Awaiting Review

#4019 fix(NetworkBehaviourInspector): Hide SyncMethod for NT
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: Awaiting Review

#4022 fix: Reset exceptionsDisconnect in Shutdown
  Assets/Mirror/Core/NetworkClient.cs
  Assets/Mirror/Core/NetworkServer.cs
  Assets/Mirror/Tests/Editor/NetworkClient/NetworkClientTests.cs
  Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
Labels: bug, Awaiting Review

#4023 chore(Tests): Update tests to use NetworkConnectionToClient everywhere
  Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourTests.cs
  Assets/Mirror/Tests/Editor/NetworkConnection/LocalConnectionTest.cs
  Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentityTests.cs
  Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
  Assets/Mirror/Tests/Editor/Rpcs/CommandTest.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourTargetRpcDuplicateName.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourTargetRpcParamNetworkConnection.cs
  Assets/Mirror/Tests/Editor/Weaver/WeaverTargetRpcTests_IsSuccess/TargetRpcValid.cs
Labels: Awaiting Review

#4024 fix(NetworkBehaviourInspector): Use showSyncMethod
  Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
  Assets/Mirror/Core/NetworkBehaviour.cs
  Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Labels: enhancement, Awaiting Review
